// <auto-generated />
namespace Pylon.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProfileIsBlockProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProfileIsBlockProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201808081803037_ProfileIsBlockProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
